// -------------------------------------------------------------------
// localhost
// -------------------------------------------------------------------
### Get all diseases
GET http://localhost:8080/diseases
### Get diseases by id
GET http://localhost:8080/diseases/664f689b0524a3d9677883b9

### Create disease
POST http://localhost:8080/diseases HTTP/1.1
content-type: application/json

{
    "name": "Childhood asthma",
    "symptoms1": "A whistling or wheezing sound when breathing out",
    "whenToSeeDoctor": "Take your child to see a health care provider if you suspect that your child has asthma.",
    "cause": "Childhood asthma causes aren't fully understood.",
    "riskFactor": "Previous allergic reactions, including skin reactions, food allergies or hay fever, also called allergic rhinitis.",
    "complication": "Permanent decline in lung function.",
    "prevention": "Limit exposure to asthma triggers."
}
### PUT disease
PUT http://localhost:8080/diseases/664f69210524a3d9677883bc HTTP/1.1
content-type:application/json

{
    "name": "tetanus",
    "symptoms": "Painful muscle spasms and stiff, immovable muscles (muscle rigidity) in your jaw",
    "whenToSeeDoctor": "Tetanus is a life-threatening disease. If you have signs or symptoms of tetanus, seek emergency care.",
    "cause": "The bacterium that causes tetanus is called Clostridium tetani. The bacterium can survive in a dormant state in soil and animal feces. It's essentially shut down until it discovers a place to thrive.",
    "riskFactor": "The greatest risk factor for tetanus infection is not being vaccinated or not keeping up with the 10-year booster shots.",
    "complication": "Breathing problems",
    "prevention": "You can prevent tetanus by being vaccinated."
}
### DELETE disease
DELETE http://localhost:8080/diseases/664f69210524a3d9677883bc


// -------------------------------------------------------------------
// Render
// -------------------------------------------------------------------
###
GET https://renderurl/diseases
###
GET https://renderurl/diseases/664f689b0524a3d9677883b9

### Create disease
POST https://renderurl/diseases HTTP/1.1
content-type: application/json

{
    "name": "Childhood asthma",
    "symptoms": "A whistling or wheezing sound when breathing out",
    "whenToSeeDoctor": "Take your child to see a health care provider if you suspect that your child has asthma.",
    "cause": "Childhood asthma causes aren't fully understood.",
    "riskFactor": "Previous allergic reactions, including skin reactions, food allergies or hay fever, also called allergic rhinitis.",
    "complication": "Permanent decline in lung function.",
    "prevention": "Limit exposure to asthma triggers."
}
### PUT disease
PUT http://renderurl/diseases/663f3d0d253a1b638c24ec87 HTTP/1.1
content-type:application/json

{
    "name": "tetanus",
    "symptoms": "Painful muscle spasms and stiff, immovable muscles (muscle rigidity) in your jaw",
    "whenToSeeDoctor": "Tetanus is a life-threatening disease. If you have signs or symptoms of tetanus, seek emergency care.",
    "cause": "The bacterium that causes tetanus is called Clostridium tetani. The bacterium can survive in a dormant state in soil and animal feces. It's essentially shut down until it discovers a place to thrive.",
    "riskFactor": "The greatest risk factor for tetanus infection is not being vaccinated or not keeping up with the 10-year booster shots.",
    "complication": "Breathing problems",
    "prevention": "You can prevent tetanus by being vaccinated."
}
### DELETE disease
DELETE http://renderurl/diseases/665210c80a783b3093ca756c